### ISSUE TITLE
is this twitter dataset available for download?

### ISSUE THREAD

**Issue by huihuifan** [javierhonduco/emoji-prediction#2]
It's hard to download all the tweets as you mentioned in this post: http://hondu.co/blog/fun-with-machine-learning-and-emojis

Would it be possible for you to release the dataset and your train/test split? Perhaps via dropbox link?

Thank you!

**Comment by javierhonduco** [comment]
Hi Huihui,

Sorry that's not very convenient to download the data. I totally agree with you, it takes too many steps to get everything ready 😢.

I didn't post it here because I'm not sure if it's ok for Twitter's API terms, but _I think_ it's not.

I'm happy to help you with any questions you may have related to fetching tweets, though! 😄

Cheers,

**Comment by huihuifan** [comment]
Thank you! Got your email. Appreciate it.
